### ISSUE TITLE
Using pretrained models

### ISSUE THREAD

**Issue by ganfy** [RicherMans/text_based_depression#9]
Hi, I'm a little confused on the use of the pretrained models (from the models.zip) . Are they supposed to be used in the feature extraction, called from an extract_text_something file?

**Comment by RicherMans** [comment]
Hey,
nope these are classifiers for each respective feature.
 The extract_text_x.py extracts only the features. These features need to be fed to the classifier.

**Comment by ganfy** [comment]
So I use them in the run.py, right?

**Comment by RicherMans** [comment]
Yes,
First extract your features, then use `run.py` with `evaluate` and the respective model as input.

**Comment by ganfy** [comment]
I see, it works fine. Thank you.
